vim.cmd [[ highlight clear ]]

-- palette ---------------------------------------------------------------------

local p = {
    none      = "NONE",
    bg0       = "#22272b",
    bg1       = "#272e33",
    bg2       = "#2e383c",
    bg3       = "#374145",
    bg_red    = "#493b40",
    bg_yellow = "#45443c",
    bg_green  = "#3c4841",
    bg_blue   = "#384b55",
    bg_pink   = "#4c3743",
    fg        = "#d3c6aa",
    red       = "#e67e80",
    orange    = "#e69875",
    yellow    = "#dbbc7f",
    green     = "#a7c080",
    cyan      = "#83c092",
    blue      = "#7fbbb3",
    purple    = "#d699b6",
    grey0     = "#5f6d6a",
    grey1     = "#7a8478",
    grey2     = "#859289",
    grey3     = "#9da9a0",
}

-- highlight -------------------------------------------------------------------

---@type table<string, vim.api.keyset.highlight>
local highlights = {
    -- helper highlight groups -------------------------------------------------
    Fg       = { fg = p.fg },
    Red      = { fg = p.red },
    Orange   = { fg = p.orange },
    Yellow   = { fg = p.yellow },
    Green    = { fg = p.green },
    Cyan     = { fg = p.cyan },
    Blue     = { fg = p.blue },
    Purple   = { fg = p.purple },
    DarkGrey = { fg = p.grey0 },
    Grey     = { fg = p.grey2 },
    Bold     = { bold = true },
    Italic   = { italic = true },
    Strike   = { strikethrough = true },
    Link     = { fg = p.blue, italic = true },

    -- vim highlights ----------------------------------------------------------
    Added            = { link = "Green" },
    Changed          = { link = "Yellow" },
    ColorColumn      = { bg = p.bg1 },
    Conceal          = { fg = p.grey0 },
    CurSearch        = { link = "IncSearch" },
    Cursor           = { reverse = true },
    CursorColumn     = { bg = p.bg2 },
    CursorIM         = { link = "Cursor" },
    CursorLine       = { bg = p.bg2 },
    CursorLineNr     = { fg = p.green, bg = p.bg2 },
    CursorLineSign   = { fg = p.green, bg = p.bg2 },
    Debug            = { fg = p.orange },
    DiffAdd          = { bg = p.bg_green },
    DiffChange       = { bg = p.bg_blue },
    DiffDelete       = { bg = p.bg_red },
    DiffText         = { fg = p.bg0, bg = p.blue },
    Directory        = { fg = p.yellow, bold = true },
    EndOfBuffer      = { fg = p.bg0 },
    ErrorMsg         = { fg = p.red, bold = true },
    FloatBorder      = { fg = p.grey1, bg = p.bg1 },
    FloatTitle       = { fg = p.grey1, bg = p.bg2, bold = true },
    FoldColumn       = { fg = p.grey1, bg = p.bg1 },
    Folded           = { fg = p.grey1, bg = p.bg1 },
    IncSearch        = { fg = p.bg0, bg = p.red },
    LineNr           = { fg = p.grey0 },
    LineNrAbove      = { fg = p.grey0 },
    LineNrBelow      = { fg = p.grey0 },
    MatchParen       = { bg = p.bg4 },
    ModeMsg          = { bold = true },
    MoreMsg          = { fg = p.yellow, bold = true },
    NonText          = { fg = p.grey0 },
    Normal           = { fg = p.fg, bg = p.bg0 },
    NormalFloat      = { fg = p.fg, bg = p.bg1 },
    NormalNC         = { fg = p.fg, bg = p.bg0 },
    Pmenu            = { fg = p.fg, bg = p.bg2 },
    PmenuSbar        = { fg = p.none, bg = p.bg2 },
    PmenuSel         = { fg = p.green, bg = p.bg_green },
    PmenuThumb       = { bg = p.grey0 },
    Question         = { fg = p.yellow },
    QuickFixLine     = { fg = p.purple, bold = true },
    Removed          = { link = "Red" },
    Search           = { fg = p.bg0, bg = p.green },
    SignColumn       = { bg = p.bg0 },
    SpecialKey       = { fg = p.yellow, bg = p.none },
    SpellBad         = { undercurl = true, sp = p.red },
    SpellCap         = { undercurl = true, sp = p.blue },
    SpellLocal       = { undercurl = true, sp = p.cyan },
    SpellRare        = { undercurl = true, sp = p.purple },
    StatusLine       = { fg = p.grey1, bg = p.bg2 },
    StatusLineNC     = { fg = p.grey0, bg = p.bg2 },
    StatusLineTerm   = { fg = p.grey2, bg = p.grey },
    StatusLineTermNC = { fg = p.grey0, bg = p.bg2 },
    Substitute       = { fg = p.bg0, bg = p.yellow },
    TabLine          = { fg = p.grey1, bg = p.bg1 },
    TabLineFill      = { fg = p.grey1, bg = p.bg1 },
    TabLineSel       = { fg = p.green, bg = p.bg_green },
    TermCursor       = { link = "Cursor" },
    TermCursorNC     = { link = "Cursor" },
    Terminal         = { fg = p.fg, bg = p.bg0 },
    Title            = { fg = p.orange, bold = true },
    VertSplit        = { fg = p.bg1, bg = p.bg1 },
    Visual           = { bg = p.bg_pink },
    VisualNOS        = { bg = p.bg_pink },
    WarningMsg       = { fg = p.yellow, bg = p.none, bold = true, },
    Whitespace       = { fg = p.grey0 },
    WildMenu         = { link = "PmenuSel" },
    WinBar           = { fg = p.grey1, bg = p.bg1 },
    WinBarNC         = { fg = p.grey0, bg = p.bg1 },
    WinSeparator     = { link = "VertSplit" },
    lCursor          = { link = "Cursor" },

    -- syntax highlights -------------------------------------------------------
    Boolean        = { link = "Purple" },
    Character      = { link = "Cyan" },
    Comment        = { link = "Grey", italic = true },
    Conditional    = { link = "Red" },
    Constant       = { link = "Fg" },
    Define         = { link = "Red" },
    Delimiter      = { fg = p.grey3 },
    Error          = { link = "Red" },
    Exception      = { link = "Red" },
    Float          = { link = "Purple" },
    Function       = { link = "Green" },
    Identifier     = { link = "Blue" },
    Ignore         = { link = "Grey" },
    Include        = { link = "Red" },
    Keyword        = { link = "Red" },
    Label          = { link = "Orange" },
    Macro          = { link = "Green" },
    Number         = { link = "Purple" },
    Operator       = { link = "Orange" },
    PreCondit      = { link = "Red" },
    PreProc        = { link = "Red" },
    Repeat         = { link = "Red" },
    Special        = { link = "Yellow" },
    SpecialChar    = { link = "Green" },
    SpecialComment = { link = "Grey" },
    Statement      = { link = "Red" },
    StorageClass   = { link = "Orange" },
    String         = { link = "Cyan" },
    Structure      = { link = "Orange" },
    Tag            = { link = "Orange" },
    Todo           = { fg = p.bg0, bg = p.blue, bold = true },
    Type           = { link = "Yellow" },
    Typedef        = { link = "Red" },

    -- treesitter --------------------------------------------------------------
    ["@annotation"]              = { link = "Purple" },
    ["@attribute"]               = { link = "Purple" },
    ["@boolean"]                 = { link = "Boolean" },
    ["@character"]               = { link = "Character" },
    ["@character.special"]       = { link = "SpecialChar" },
    ["@comment"]                 = { fg = p.grey0, italic = true },
    ["@comment.documentation"]   = { link = "Comment" },
    ["@comment.error"]           = { fg = p.bg0, bg = p.red, bold = true },
    ["@comment.note"]            = { fg = p.bg0, bg = p.green, bold = true },
    ["@comment.todo"]            = { link = "Todo" },
    ["@comment.warning"]         = { fg = p.bg0, bg = p.yellow, bold = true },
    ["@conceal"]                 = { link = "Grey" },
    ["@conditional"]             = { link = "Conditional" },
    ["@constant"]                = { link = "Constant" },
    ["@constant.builtin"]        = { link = "Orange" },
    ["@constant.macro"]          = { link = "Macro" },
    ["@constant.regex"]          = { link = "String" },
    ["@constructor"]             = { link = "Function" },
    ["@debug"]                   = { link = "Debug" },
    ["@define"]                  = { link = "Define" },
    ["@diff.delta"]              = { link = "Changed" },
    ["@diff.minus"]              = { link = "Removed" },
    ["@diff.plus"]               = { link = "Added" },
    ["@error"]                   = { link = "Error" },
    ["@exception"]               = { link = "Exception" },
    ["@field"]                   = { link = "Identifier" },
    ["@float"]                   = { link = "Float" },
    ["@function"]                = { link = "Function" },
    ["@function.builtin"]        = { link = "Orange" },
    ["@function.macro"]          = { link = "Macro" },
    ["@include"]                 = { link = "Include" },
    ["@keyword"]                 = { link = "Keyword" },
    ["@keyword.debug"]           = { link = "Debug" },
    ["@keyword.function"]        = { link = "Keyword" },
    ["@keyword.modifier"]        = { link = "StorageClass" },
    ["@keyword.operator"]        = { link = "Operator" },
    ["@keyword.storage"]         = { link = "StorageClass" },
    ["@label"]                   = { link = "Label" },
    ["@markup.emphasis"]         = { link = "Bold" },
    ["@markup.environment"]      = { link = "Purple" },
    ["@markup.environment.name"] = { link = "Purple" },
    ["@markup.heading"]          = { link = "Title" },
    ["@markup.italic"]           = { link = "Italic" },
    ["@markup.link"]             = { link = "Link" },
    ["@markup.link.label"]       = { link = "String" },
    ["@markup.link.url"]         = { link = "Link" },
    ["@markup.list"]             = { link = "Delimiter" },
    ["@markup.list.checked"]     = { link = "Green" },
    ["@markup.list.unchecked"]   = { link = "Ignore" },
    ["@markup.math"]             = { link = "Blue" },
    ["@markup.quote"]            = { link = "Grey" },
    ["@markup.raw"]              = { link = "String" },
    ["@markup.strike"]           = { link = "Strike" },
    ["@markup.strong"]           = { link = "Bold" },
    ["@markup.underline"]        = { link = "Underlined" },
    ["@math"]                    = { link = "Blue" },
    ["@method"]                  = { link = "Function" },
    ["@module"]                  = { link = "Yellow" },
    ["@namespace"]               = { link = "Yellow" },
    ["@none"]                    = { link = "None" },
    ["@number"]                  = { link = "Number" },
    ["@operator"]                = { link = "Operator" },
    ["@parameter"]               = { link = "Identifier" },
    ["@parameter.reference"]     = { link = "Identifier" },
    ["@preproc"]                 = { link = "PreProc" },
    ["@property"]                = { link = "Identifier" },
    ["@punctuation.bracket"]     = { link = "Delimiter" },
    ["@punctuation.delimiter"]   = { link = "Delimiter" },
    ["@punctuation.special"]     = { link = "Special" },
    ["@repeat"]                  = { link = "Repeat" },
    ["@storageclass"]            = { link = "StorageClass" },
    ["@storageclass.lifetime"]   = { link = "StorageClass" },
    ["@strike"]                  = { link = "Strike" },
    ["@string"]                  = { link = "String" },
    ["@string.documentation"]    = { link = "@coment.documentation" },
    ["@string.escape"]           = { link = "SpecialChar" },
    ["@string.regex"]            = { link = "String" },
    ["@string.regexp"]           = { link = "String" },
    ["@string.special"]          = { link = "SpecialChar" },
    ["@string.special.symbol"]   = { link = "SpecialChar" },
    ["@string.special.url"]      = { link = "Link" },
    ["@symbol"]                  = { link = "Label" },
    ["@tag"]                     = { link = "Tag" },
    ["@tag.attribute"]           = { link = "@attribute" },
    ["@tag.delimiter"]           = { link = "Delimiter" },
    ["@text"]                    = { link = "Fg" },
    ["@text.danger"]             = { link = "Error" },
    ["@text.diff.add"]           = { link = "Added" },
    ["@text.diff.delete"]        = { link = "Removed" },
    ["@text.emphasis"]           = { link = "@markup.emphasis" },
    ["@text.environment"]        = { link = "@markup.environment" },
    ["@text.environment.name"]   = { link = "@markup.environment.name" },
    ["@text.gitcommit"]          = { link = "Blue" },
    ["@text.html"]               = { link = "Purple" },
    ["@text.literal"]            = { link = "String" },
    ["@text.math"]               = { link = "@markup.math" },
    ["@text.note"]               = { link = "Green" },
    ["@text.reference"]          = { link = "Link" },
    ["@text.strike"]             = { link = "Strike" },
    ["@text.strong"]             = { link = "Bold" },
    ["@text.title"]              = { link = "Title" },
    ["@text.todo"]               = { link = "Todo" },
    ["@text.todo.checked"]       = { link = "@markup.list.checked" },
    ["@text.todo.unchecked"]     = { link = "@markup.list.unchecked" },
    ["@text.underline"]          = { link = "Underlined" },
    ["@text.uri"]                = { link = "Link" },
    ["@text.warning"]            = { link = "Yellow" },
    ["@todo"]                    = { link = "Todo" },
    ["@type"]                    = { link = "Type" },
    ["@type.builtin"]            = { link = "Type" },
    ["@type.definition"]         = { link = "Typedef" },
    ["@type.qualifier"]          = { link = "StorageClass" },
    ["@uri"]                     = { link = "Link" },
    ["@variable"]                = { link = "Fg" },
    ["@variable.builtin"]        = { link = "Orange" },
    ["@variable.member"]         = { link = "Identifier" },
    ["@variable.parameter"]      = { link = "Identifier" },

    -- language specific treesitter overrides ----------------------------------
    ["@attribute.zig"]                    = { link = "@keyword" },
    ["@constructor.lua"]                  = { link = "Delimiter" },
    ["@function.builtin.zig"]             = { link = "Orange" },
    ["@keyword.import.zig"]               = { link = "Orange" },
    ["@keyword.modifier.zig"]             = { link = "@keyword" },
    ["@markup.heading.1.markdown"]        = { fg = p.red, bold = true },
    ["@markup.heading.2.markdown"]        = { fg = p.orange, bold = true },
    ["@markup.heading.3.markdown"]        = { fg = p.yellow, bold = true },
    ["@markup.heading.4.markdown"]        = { fg = p.green, bold = true },
    ["@markup.heading.5.markdown"]        = { fg = p.blue, bold = true },
    ["@markup.heading.6.markdown"]        = { fg = p.purple, bold = true },
    ["@markup.heading.1.marker.markdown"] = { fg = p.grey0 },
    ["@markup.heading.2.marker.markdown"] = { fg = p.grey0 },
    ["@markup.heading.3.marker.markdown"] = { fg = p.grey0 },
    ["@markup.heading.4.marker.markdown"] = { fg = p.grey0 },
    ["@markup.heading.5.marker.markdown"] = { fg = p.grey0 },
    ["@markup.heading.6.marker.markdown"] = { fg = p.grey0 },
    ["@markup.heading.ini"]               = { link = "Orange", bold = false },
    ["@punctuation.special.rust"]         = { link = "@punctuation.delimiter" },

    -- diagnostics -------------------------------------------------------------
    DiagnosticError = { fg = p.red },
    DiagnosticWarn = { fg = p.yellow },
    DiagnosticInfo = { fg = p.blue },
    DiagnosticHint = { fg = p.green },
    DiagnosticUnnecessary = { undercurl = true, sp = p.grey2 },
    DiagnosticFloatingError = { fg = p.red },
    DiagnosticFloatingWarn = { fg = p.yellow },
    DiagnosticFloatingInfo = { fg = p.blue },
    DiagnosticFloatingHint = { fg = p.green },
    DiagnosticVirtualTextError = { fg = p.red },
    DiagnosticVirtualTextWarn = { fg = p.yellow },
    DiagnosticVirtualTextInfo = { fg = p.blue },
    DiagnosticVirtualTextHint = { fg = p.green },
    DiagnosticUnderlineError = { undercurl = true, sp = p.red },
    DiagnosticUnderlineWarn = { undercurl = true, sp = p.yellow },
    DiagnosticUnderlineInfo = { undercurl = true, sp = p.blue },
    DiagnosticUnderlineHint = { undercurl = true, sp = p.green },
    DiagnosticSignError = { fg = p.red },
    DiagnosticSignWarn = { fg = p.yellow },
    DiagnosticSignInfo = { fg = p.blue },
    DiagnosticSignHint = { fg = p.green },

    -- custom groups -----------------------------------------------------------
    StatusLineFilename = { fg = p.green, bg = p.bg2 },
    StatusLineGrey     = { fg = p.grey1, bg = p.bg2 },
    StatusLineLocation = { fg = p.cyan, bg = p.bg2 },
    StatusLineModified = { fg = p.yellow, bg = p.bg2 },
}

-- apply highlighting rules ----------------------------------------------------

for group, settings in pairs (highlights) do
    vim.api.nvim_set_hl (0, group, settings)
end
