[font]
normal = { family = "DM Mono" }
size = 11

[colors.primary]
background = '#22272b'
foreground = '#d3c6aa'

[colors.normal]
black   = '#5f6d6a'
red     = '#e67e80'
green   = '#a7c080'
yellow  = '#dbbc7f'
blue    = '#7fbbb3'
magenta = '#d699b6'
cyan    = '#83c092'
white   = '#d3c6aa'

[colors.bright]
black   = '#5f6d6a'
red     = '#e67e80'
green   = '#a7c080'
yellow  = '#dbbc7f'
blue    = '#7fbbb3'
magenta = '#d699b6'
cyan    = '#83c092'
white   = '#d3c6aa'

[colors.cursor]
text   = "#22272b"
cursor = "#d3c6aa"

[cursor]
unfocused_hollow = false
thickness = 0.2

[mouse]
hide_when_typing = true
